### ISSUE TITLE
请问Android Demo中几个libXXX_java.so文件是怎么编译出来的???

### ISSUE THREAD

**Issue by h3clikejava** [SeetaFace6Open/FaceBoxes#1]
如果不用那几个_java.so文件，会报错

 Process: com.timehut.aiface, PID: 25793
    java.lang.UnsatisfiedLinkError: No implementation found for void com.seeta.sdk.FaceDetector.construct(com.seeta.sdk.SeetaModelSetting) (tried Java_com_seeta_sdk_FaceDetector_construct and Java_com_seeta_sdk_FaceDetector_construct__Lcom_seeta_sdk_SeetaModelSetting_2)
        at com.seeta.sdk.FaceDetector.construct(Native Method)
        at com.seeta.sdk.FaceDetector.<init>(FaceDetector.java:32)

**Comment by JaydipKalkani** [comment]
@h3clikejava did you found any solution for this. I am facing the same error.
